# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16ecfbf3a8785f4a823e6fdba77724d058ce5301708cd61ec87b39ff05c51eebdc311257e3be9e7a2bf4d40eb13d9a01ae866f9f33130838198cb9159e112034

test:
  secret_key_base: b34184981560fcf69034029948b3437461af167dcdbec1e37ae751f0c8fdffd3bbb2f0473be5cd0f2af2307327d548d83ae0be31997b455d4b6e0e560b5234ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
